name: logistics_dbt
version: '1.0.0'
config-version: 2

profile: logistics_dbt

vars:
  data_date: '1900-01-01'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  logistics_dbt:
    gold:
      +materialized: table
